/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab04;

import org.apache.commons.math3.geometry.spherical.oned.ArcsSet;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.util.stream.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

class SplittingTest {


    @ParameterizedTest
    @MethodSource("generator")
    void canBalanceTest(String description, boolean expected, int[] array){
        assertEquals(expected, Splitting.canBalance(array));

    }

    private static Stream<Arguments> generator(){

        return Stream.of(
                Arguments.of("A null array", false, null),
                Arguments.of("An empty array thats been initialized", false, new int[]{}),
                Arguments.of("An array with all of the same element and odd number of elements", false, new int[]{10,10,10}),
                Arguments.of("An array whose sum is odd", false, new int[]{10, 3, 2})

        );
    }


}