/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

import com.google.common.annotations.VisibleForTesting;

import java.util.Locale;

public class Rectangle {



    private int x;
    private int y;
    private int width;
    private int height;
    public Rectangle(){
        x = 0;
        y = 0;
        width = 1;
        height = 1;

    }

    public Rectangle(int x, int y, int width, int height){
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;


    }

    public int stringLength(String string){
        return string.length();
    }

    public boolean palindromeCheck(String string){
        String theString = string.toLowerCase(Locale.ROOT);
        int length = string.length();
        for (int i = 0; i < length; i++){
            if (theString.charAt(i) != theString.charAt(length-1-i)){
                return false;
            }
        }
        return true;
    }
    public int factorialProgram(int input){
        int output = 1;
        if (input < 0 ){
            for (int i = -1; i >= input; i++) {
                output = output * i;


            }
        }
        if (input >= 0) {
            for (int i = 1; i <= input; i++) {
                output = output * i;
                System.out.println(output);


            }
        }
        return output;
    }

    //Armstrong numbers

    public int getX() { return x; }
    public int getY() { return y; }
    public int getWidth() { return width; }
    public int getHeight() { return height; }

    public void setWidth(int width) throws IllegalArgumentException{
        if (width >= 0) {
            this.width = width;
        }else{
            throw new IllegalArgumentException();
        }

    }

    public void setHeight(int height) throws IllegalArgumentException{
        if ( height >= 0) {
            this.height = height;
        }else{
            throw new IllegalArgumentException();
        }

    }

    public void setX(int x){
        if ( x >= 0) {
            this.x = x;
        }else{
            throw new IllegalArgumentException();
        }
    }

    public void setY(int y){
        if ( y >= 0) {
            this.y = y;
        }else{
            throw new IllegalArgumentException();
        }

    }




    //Two equal rectangles simply need to have the same height and width and both be rectangles
    @Override
    public boolean equals(Object otherObject){
        if (otherObject instanceof Rectangle ){
            Rectangle otherRect = (Rectangle) otherObject;

            if ( (otherRect.getHeight() == this.getHeight()) && (otherRect.getWidth() == this.getWidth())){
                return true;
            }
        }
        return false;
    }

}
